# Generated by Django 4.2 on 2024-02-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_productoimagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoimagen',
            options={'verbose_name_plural': 'Imagenes del Producto'},
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
