# Generated by Django 4.2 on 2024-02-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_productoimagen_options_producto_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoimagen',
            options={'verbose_name': 'Imagen del Producto', 'verbose_name_plural': 'Imagenes del Producto'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
