# Generated by Django 4.2 on 2024-03-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_pedido_pedidodetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidodetalle',
            name='precio',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('0', 'Solicitado'), ('1', 'Pagado')], default='0', max_length=1),
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='tbl_pedido',
        ),
    ]
